version: '3'
services:
  node:
    build: ./server/
    ports:
     - "3001:3001"
    volumes:
      - ./server/:/home/app
      - /home/app/node_modules
  reactjs:
    build: ./client/
    ports:
     - "3000:3000"
    volumes:
      - ./client/:/home/app
      - /home/app/node_modules